language:
  - node_js
node_js:
  - '5'
before_install:
  # Setup `Chrome` instance.
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - npm install gulpjs/gulp-cli#4.0 -g
  - npm install typings -g
install:
  - npm install
before_script:
  - gulp build
script:
  - gulp unit
